export * from './CartPage/CartPage';
export * from './CatalogPage/CatalogPage';
export * from './CustomerPage/CustomerPage';
export * from './DealsPage/DealsPage';
export * from './InformationPage/InformationPage';
export * from './MainPage/MainPage';
export * from './NotFoundPage/NotFoundPage';
export * from './ProductsCatalogPage/ProductsCatalogPage';
export * from './ProductDetailsPage/ProductDetailsPage';
